name: Auto Commit

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'public/**'
      - 'package.json'
      - 'package-lock.json'
      - 'tsconfig.json'

permissions:
  contents: write
  actions: write

jobs:
  format-and-commit:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, 'chore: auto-format') && github.event.head_commit.author.email != 'action@github.com'"
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci --prefer-offline --no-audit
      
    - name: Run code formatting
      run: |
        # Format TypeScript/JavaScript files
        npm run format || npx prettier --write "src/**/*.{ts,tsx,js,jsx,css,md}" --ignore-unknown
        
        # Fix linting issues automatically  
        npm run lint -- --fix || echo "Linting completed with warnings"
        
    - name: Check for changes
      id: verify-changed-files
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "changed=true" >> $GITHUB_OUTPUT
          echo "Files were changed by formatting"
        else
          echo "changed=false" >> $GITHUB_OUTPUT
          echo "No files were changed by formatting"
        fi
        
    - name: Commit formatted files
      if: steps.verify-changed-files.outputs.changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "chore: auto-format code [skip ci]"
        git push