name: Auto Commit

on:
  schedule:
    # Run every hour during development (can be adjusted)
    - cron: '0 * * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      run: npm test -- --passWithNoTests
      
    - name: Build project
      run: npm run build
      
    - name: Configure Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
    - name: Check for changes
      id: changes
      run: |
        git add -A
        if git diff --staged --quiet; then
          echo "No changes to commit"
          echo "::set-output name=changes::false"
        else
          echo "Changes detected"
          echo "::set-output name=changes::true"
        fi
        
    - name: Commit changes
      if: steps.changes.outputs.changes == 'true'
      run: |
        git commit -m "chore: automated commit with build artifacts
        
        - Updated build artifacts
        - Automated commit from GitHub Actions
        - Timestamp: $(date -u)"
        
    - name: Push changes
      if: steps.changes.outputs.changes == 'true'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main